"""Database initialization entry point.

Creates the SQLite schema from the ORM metadata and optionally seeds it from
``data/devices.json``.

Usage::

    python -m app.database.init_db              # create tables + seed
    python -m app.database.init_db --reset      # drop, recreate, then seed
    python -m app.database.init_db --no-seed    # create tables only
    python -m app.database.init_db --seed-path data/devices.json
"""

from __future__ import annotations

import argparse
import json
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from sqlalchemy import Engine, func, select
from sqlalchemy.orm import Session, sessionmaker

from app.config import get_settings
from app.database import session as db_session
from app.database.base import Base
from app.database.models import Device

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SEED_PATH = PROJECT_ROOT / "data" / "devices.json"

# Fields accepted from the seed file. ``id`` is generated by the database.
SEED_FIELDS = (
    "device_id",
    "device_name",
    "device_type",
    "location",
    "status",
    "temperature",
    "pressure",
    "rpm",
    "alarm_code",
    "last_maintenance_time",
)


@dataclass
class InitResult:
    """Summary of an initialization run."""

    database_url: str
    reset: bool
    seeded: int
    total: int


def ensure_sqlite_directory(database_url: str) -> None:
    """Create the parent directory of a SQLite file so ``create_all`` works."""
    if not database_url.startswith("sqlite"):
        return
    raw = database_url.replace("sqlite:///", "", 1)
    if not raw or raw == ":memory:":
        return
    path = Path(raw)
    if not path.is_absolute():
        path = Path.cwd() / path
    path.parent.mkdir(parents=True, exist_ok=True)


def parse_datetime(value: Any) -> datetime | None:
    """Parse an ISO-8601 string into ``datetime``, tolerating null values."""
    if value in (None, ""):
        return None
    if isinstance(value, datetime):
        return value
    return datetime.fromisoformat(str(value))


def load_seed_records(seed_path: Path | str = DEFAULT_SEED_PATH) -> list[dict[str, Any]]:
    """Load the seed JSON file as a list of device dictionaries."""
    path = Path(seed_path)
    if not path.exists():
        raise FileNotFoundError(f"Seed file not found: {path}")
    with path.open("r", encoding="utf-8") as handle:
        payload = json.load(handle)
    if not isinstance(payload, list):
        raise ValueError(f"Seed file must contain a JSON list of devices: {path}")
    return payload


def create_tables(engine: Engine | None = None) -> None:
    """Create all tables declared on the ORM metadata."""
    Base.metadata.create_all(bind=engine or db_session.engine)


def drop_tables(engine: Engine | None = None) -> None:
    """Drop all tables declared on the ORM metadata."""
    Base.metadata.drop_all(bind=engine or db_session.engine)


def seed_devices(records: Sequence[dict[str, Any]], session: Session) -> int:
    """Upsert devices by ``device_id``. Returns the number of records written."""
    written = 0
    for record in records:
        device_id = record.get("device_id")
        if not device_id:
            continue

        device = session.scalar(select(Device).where(Device.device_id == device_id))
        if device is None:
            device = Device(device_id=device_id)
            session.add(device)

        for field in SEED_FIELDS:
            if field == "device_id" or field not in record:
                continue
            value = record[field]
            if field == "last_maintenance_time":
                value = parse_datetime(value)
            setattr(device, field, value)

        written += 1

    session.commit()
    return written


def count_devices(session: Session) -> int:
    """Return the total number of device rows."""
    return int(session.scalar(select(func.count()).select_from(Device)) or 0)


def init_db(
    *,
    seed: bool = True,
    reset: bool = False,
    seed_path: Path | str = DEFAULT_SEED_PATH,
    engine: Engine | None = None,
    session_factory: sessionmaker | None = None,
) -> InitResult:
    """Create the schema and optionally seed it.

    The ``engine`` and ``session_factory`` arguments allow tests to target an
    isolated database while production uses the module-level defaults.
    """
    bind = engine or db_session.engine
    factory = session_factory or db_session.SessionLocal
    settings = get_settings()

    ensure_sqlite_directory(settings.database_url)

    if reset:
        drop_tables(bind)
    create_tables(bind)

    seeded = 0
    if seed:
        records = load_seed_records(seed_path)
        with factory() as session:
            seeded = seed_devices(records, session)

    with factory() as session:
        total = count_devices(session)

    return InitResult(
        database_url=settings.database_url,
        reset=reset,
        seeded=seeded,
        total=total,
    )


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI argument parser."""
    parser = argparse.ArgumentParser(
        prog="python -m app.database.init_db",
        description="Create the SQLite schema and seed device records.",
    )
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Drop existing tables before creating them.",
    )
    parser.add_argument(
        "--no-seed",
        action="store_true",
        help="Skip loading the seed file.",
    )
    parser.add_argument(
        "--seed-path",
        type=Path,
        default=DEFAULT_SEED_PATH,
        help="Path to the seed JSON file (default: data/devices.json).",
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """CLI entry point."""
    args = build_parser().parse_args(argv)
    result = init_db(seed=not args.no_seed, reset=args.reset, seed_path=args.seed_path)

    print(f"database : {result.database_url}")
    print(f"reset    : {result.reset}")
    print(f"seeded   : {result.seeded}")
    print(f"total    : {result.total}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
